AutoPlus/Entities/Brands.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AutoPlus.Entities
{
    public class Brands
    {
        public int Id { get; set; }
        public string ModelTypeID { get; set; }
        public string Brand { get; set; }

        
    }
}

AutoPlus/Areas/Admin/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoPlus.Data;
using AutoPlus.Entities;
using Microsoft.AspNetCore.Authorization;

namespace AutoPlus.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Admin/Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brands = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brands == null)
            {
                return NotFound();
            }

            return View(brands);
        }

        // GET: Admin/Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Brand")] Brands brands)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brands);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brands);
        }

        // GET: Admin/Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brands = await _context.Brands.FindAsync(id);
            if (brands == null)
            {
                return NotFound();
            }
            return View(brands);
        }

        // POST: Admin/Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Brand")] Brands brands)
        {
            if (id != brands.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brands);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandsExists(brands.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brands);
        }

        // GET: Admin/Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brands = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brands == null)
            {
                return NotFound();
            }

            return View(brands);
        }

        // POST: Admin/Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brands = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brands);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandsExists(int id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }
    }
}

AutoPlus/Areas/Admin/Controllers/ModelBrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoPlus.Data;
using AutoPlus.Entities;
using Microsoft.AspNetCore.Authorization;

namespace AutoPlus.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ModelBrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModelBrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/ModelBrands
        public async Task<IActionResult> Index(int Idbrand)
        {
            List<ModelBrands> list = await (from catItem in _context.ModelBrands
                                            where
       catItem.IdBrand == Idbrand
                                            select new ModelBrands
                                            {
                                                Id = catItem.Id,
                                                IdBrand = Idbrand,
                                                Model = catItem.Model,
                                                ModelTypes = catItem.ModelTypes
                                            }
                                            ).ToListAsync();


            ViewBag.IdBrand = Idbrand;
            return View(list);
        }

            // GET: Admin/ModelBrands/Details/5
            public async Task<IActionResult> Details(int? id)
            {
            if (id == null)
            {
                return NotFound();
            }

            var modelBrands = await _context.ModelBrands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelBrands == null)
            {
                return NotFound();
            }

            return View(modelBrands);
           }

        // GET: Admin/ModelBrands/Create
        public IActionResult Create(int Idbrand)
        {
            ModelBrands modelBrands = new ModelBrands
            {
                IdBrand = Idbrand
            };
            return View(modelBrands);
        }

        // POST: Admin/ModelBrands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdBrand,Model")] ModelBrands modelBrands)
        {
            if (ModelState.IsValid)
            {
                _context.Add(modelBrands);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index),new {Idbrand = modelBrands.IdBrand});
            }
            return View(modelBrands);
        }

        // GET: Admin/ModelBrands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelBrands = await _context.ModelBrands.FindAsync(id);
            if (modelBrands == null)
            {
                return NotFound();
            }
            return View(modelBrands);
        }

        // POST: Admin/ModelBrands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdBrand,Model")] ModelBrands modelBrands)
        {
            if (id != modelBrands.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(modelBrands);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelBrandsExists(modelBrands.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { Idbrand = modelBrands.IdBrand });
            }
            return View(modelBrands);
        }

        // GET: Admin/ModelBrands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var modelBrands = await _context.ModelBrands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (modelBrands == null)
            {
                return NotFound();
            }

            return View(modelBrands);
        }

        // POST: Admin/ModelBrands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var modelBrands = await _context.ModelBrands.FindAsync(id);
            _context.ModelBrands.Remove(modelBrands);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { Idbrand = modelBrands.IdBrand });
        }

        private bool ModelBrandsExists(int id)
        {
            return _context.ModelBrands.Any(e => e.Id == id);
        }
    }
}

AutoPlus/Areas/Admin/Views/Brands/Create.cshtml
@model AutoPlus.Entities.Brands

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Brands</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoPlus/Areas/Admin/Views/Brands/Delete.cshtml
@model AutoPlus.Entities.Brands

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brands</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AutoPlus/Areas/Admin/Views/Brands/Details.cshtml
@model AutoPlus.Entities.Brands

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Brands</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AutoPlus/Areas/Admin/Views/Brands/Edit.cshtml
@model AutoPlus.Entities.Brands

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Brands</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AutoPlus/Areas/Admin/Views/Brands/Index.cshtml
@model IEnumerable<AutoPlus.Entities.Brands>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-controller="ModelBrands" asp-action="Index" asp-route-IdBrand="@item.Id">Update</a>
            </td>
        </tr>
}
    </tbody>
</table>